<a href="https://colab.research.google.com/github/Kayumov094/Datani_tozalash/blob/main/Datani_tozalash_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/mukhammad-irmatov/health_dataset/main/healt_info.csv")
df.head(3)

,Sno,AGE,SEX,CASTE_NAME,CATEGORY_CODE,CATEGORY_NAME,SURGERY_CODE,SURGERY,VILLAGE,MANDAL_NAME,...,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,HOSP_DISTRICT,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,Ponduru,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,Kaviti,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,Kaviti,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D

In [ ]:
df.info() # data haqida informatsiya oldik

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335394 entries, 0 to 335393
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Sno               335394 non-null  int64
 1   AGE               335394 non-null  int64
 2   SEX               335394 non-null  object
 3   CASTE_NAME        335394 non-null  object
 4   CATEGORY_CODE     335394 non-null  object
 5   CATEGORY_NAME     335394 non-null  object
 6   SURGERY_CODE      335394 non-null  object
 7   SURGERY           335394 non-null  object
 8   VILLAGE           335394 non-null  object
 9   MANDAL_NAME       335394 non-null  object
 10  DISTRICT_NAME     335394 non-null  object
 11  PREAUTH_DATE      335394 non-null  object
 12  PREAUTH_AMT       335394 non-null  int64
 13  CLAIM_DATE        335394 non-null  object
 14  CLAIM_AMOUNT      335394 non-null  int64
 15  HOSP_NAME         335394 non-null  object
 16  HOSP_TYPE         335394 non-null  object
 17  HOSP_DISTRICT     335394 non-null  object
 18  SURGERY_DATE      335394 non-null  object
 19  DISCHARGE_DATE    332717 non-null  object
 20  Mortality Y / N   335394 non-null  object
 21  MORTALITY_DATE    8238 non-null    object
 22  SRC_REGISTRATION  335394 non-null  object
dtypes: int64(4), object(19)
memory usage: 58.9+ MB

In [ ]:
df.columns

Index(['Sno', 'AGE', 'SEX', 'CASTE_NAME', 'CATEGORY_CODE', 'CATEGORY_NAME',
       'SURGERY_CODE', 'SURGERY', 'VILLAGE', 'MANDAL_NAME', 'DISTRICT_NAME',
       'PREAUTH_DATE', 'PREAUTH_AMT', 'CLAIM_DATE', 'CLAIM_AMOUNT',
       'HOSP_NAME', 'HOSP_TYPE', 'HOSP_DISTRICT', 'SURGERY_DATE',
       'DISCHARGE_DATE', 'Mortality Y / N', 'MORTALITY_DATE',
       'SRC_REGISTRATION'],
      dtype='object')

In [ ]:
df.columns = [
    't_r', 'yosh', 'jinsi', 'kasta_nomi', 'kategoriya_kodi', 'kategoriya_nomi',
    'operatsiya_kodi', 'operatsiya', 'qishloq', 'familiya', 'viloyat', 'oldindan_tasdiqlash_sanasi',
    'oldindan_tasdiqlash_summasi', 'davo_sanasi', 'davo_summasi', 'shifoxona_nomi', 'shifoxona_turi',
    'shifoxona_joylashgan_viloyat', 'Operatsiya_sana', 'uyga_chiqarilgan_sana', 'hayotmi', 'olim_sanasi',
    'royxatdan_otgan_manba'
    ]
df # dtaframe dagi ustunlar nomini tusnurali qilib o'zgartirib oldim

,t_r,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,familiya,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
0,1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,Ponduru,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,Kaviti,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,Kaviti,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,4,45,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Telikipenta,Sarubujjili,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,5,54,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Thandemvalasa,Srikakulam,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,335390,65,Male,SC,S3,OPHTHALMOLOGY SURGERY,SU66,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,Ponnur,...,04-08-2017 21:23,23320,Sankar Eye Hospital,C,Guntur,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,335391,54,Female,OC,S12,MEDICAL ONCOLOGY,S12.1.4,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,Udayagiri,...,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,Hyderabad,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,335392,19,Female,SC,S12,MEDICAL ONCOLOGY,S12.28.1,Palliative Chemotherapy for unlisted Regimen,Vinduru,Gudur,...,04-10-2017 19:46,5000,M.N.J.Hospitals,G,Hyderabad,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,335393,50,Male,BC,S9,GENITO URINARY SURGERIES,S9.3.4,ursl,Duppituru,Atchutapuram,...,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,Vishakhapatnam,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,335394,46,Female,SC,S12,MEDICAL ONCOLOGY,S12.2.1,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,Mummidivaram,...,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,East Godavari,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

In [ ]:
df.head()

,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,familiya,viloyat,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
t_r,,,,,,,,,,,,,,,,,,,,,
1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,Ponduru,Srikakulam,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,Kaviti,Srikakulam,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,Kaviti,Srikakulam,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
4,45,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Telikipenta,Sarubujjili,Srikakulam,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
5,54,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Thandemvalasa,Srikakulam,Srikakulam,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D

Bu dataset sug'urta kompaniyasining real ma'lumotlardan tuzilgan. Bu datasetda 480000 qator sug'urta ma'lumotlar tashkil topgan.
Quyida datasetning ba'zi ustunlari haqida qisqacha ma'lumot

*   Sno = seriya raqami
*   AGE = yoshi
*   SEX = jinsi (female = ayol, male = erkak)
*   CASTE_NAME = kasta nomi (Hindistonda har bir inson ma'lum bir kastaga oid bo'ladi)
*   CATEGORY_CODE = kategoriya kodi
*   CATEGORY_Name = kategoriya nomi
*   SURGERY_CODE = operatsiya kodi
*   Mandal_Name = mandal nomlanishi ya'ni familiyasi desak ham bo'ladi
*   Mortality Y/N = vafot etgan yoki vafot etmaganligi
*   MORTALITY_DATE = qachon vafot etganligi

### **1-mashq**. Datasetdagi barcha takrorlangan qatorlar sonini toping

In [ ]:
# Javobni shuyerga yozing
df_duplicated = df[df.duplicated()] #duplikat ma'lumotlarni chiqarib oldim
df_duplicated # bu duplikat qilingan ma'lumotlar 30 qator 22 ustundan iborat

,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,familiya,viloyat,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
t_r,,,,,,,,,,,,,,,,,,,,,
25067,0,Female(Child),Minorities,M4,PEDIATRICS,M4.1.15,Medical Management of Term Baby Severe Hyperbi...,Machavaram,Machavaram,Guntur,...,10-01-2017 00:16,35000,"Government General Hospital, Guntur",G,Guntur,27-07-2016 00:00,30-07-2016 00:00,NO,NaN,D
42636,0,Male(Child),ST,M4,PEDIATRICS,M4.1.5,Medicalmanagement of Preterm baby of 33 To 34 ...,Undrajavaram,Undrajavaram,West Godavari,...,20-03-2017 22:43,35000,APPLE HOSPITAL A UNIT OF TANUKU HOSPITAL,C,West Godavari,03-09-2016 00:00,14-09-2016 00:00,NO,NaN,D
57793,33,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.2.7,Amniotic Membrane Graft for Cornea/Sclera (12....,Yeditha,Mandapeta,East Godavari,...,12-01-2017 00:43,11000,AKIRA EYE HOSPITAL,C,East Godavari,28-09-2016 00:00,30-09-2016 00:00,NO,NaN,D
58764,44,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,22nd Ward,Bhimavaram Municipal,West Godavari,...,12-01-2017 00:39,2000,AKIRA EYE HOSPITAL,C,East Godavari,29-09-2016 00:00,30-09-2016 00:00,NO,NaN,D
77985,9,Female(Child),BC,S2,ENT SURGERY,S2.1.5,Myringotomy with grommet for one ear,Epuru Palem,Chirala,Prakasam,...,11-01-2017 22:30,10200,Nalluri Nursing Home,C,Prakasam,23-10-2016 00:00,24-10-2016 00:00,NO,NaN,D
103125,72,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,B. Savaram,Razole,East Godavari,...,11-01-2017 21:50,2040,Pushpagiri Eye Hospital,C,Hyderabad,17-11-2016 00:00,19-11-2016 00:00,NO,NaN,D
123861,61,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Koruturu,Indukurpet,Nellore,...,20-01-2017 19:20,2000,Modern Eye Hospital and Research Centre,C,Nellore,06-12-2016 00:00,06-12-2016 00:00,NO,NaN,D
157561,43,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Ojili,Ojili,Nellore,...,17-02-2017 19:18,2000,Modern Eye Hospital and Research Centre,C,Nellore,05-01-2017 00:00,05-01-2017 00:00,NO,NaN,D
158757,40,Male,OC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,11th Ward,Rajahmundry(M),East Godavari,...,01-03-2017 21:18,2000,AKIRA EYE HOSPITAL,C,East Godavari,09-01-2017 00:00,09-01-2017 00:00,NO,NaN,D
168315,51,Male,OC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Butchireddypalem,Butchireddipalem,Nellore,...,08-03-2017 19:27,2000,Modern Eye Hospital and Research Centre,C,Nellore,18-01-2017 00:00,18-01-2017 00:00,NO,NaN,D
184776,47,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Malakapalle,Tallapudi,West Godavari,...,17-03-2017 20:03,2000,AKIRA EYE HOSPITAL,C,East Godavari,31-01-2017 00:00,01-02-2017 00:00,NO,NaN,D
197247,49,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Srirangapatnam,Korukonda,East Godavari,...,22-03-2017 21:13,2000,Goutami Eye Institute,C,East Godavari,11-02-2017 00:00,11-02-2017 00:00,NO,NaN,D
214716,48,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Kunavaram,Uppalaguptam,East Godavari,...,06-04-2017 21:36,2000,Goutami Eye Institute,C,East Godavari,25-02-2017 00:00,25-02-2017 00:00,NO,NaN,D
220375,35,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Potluru,Gudluru,Prakasam,...,06-04-2017 21:08,2000,Modern Eye Hospital and Research Centre,C,Nellore,02-03-2017 00:00,02-03-2017 00:00,NO,NaN,D
227266,65,Male,OC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Ward-16,Proddutur,YSR Kadapa,...,17-04-2017 20:09,2000,Modern Eye Hospital and Research Centre,C,Nellore,08-03-2017 00:00,08-03-2017 00:00,NO,NaN,D
231190,57,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Kotapadu,Ponnaluru,Prakasam,...,19-04-2017 20:44,2000,Modern Eye Hospital and Research Centre,C,Nellore,11-03-2017 00:00,11-03-2017 00:00,NO,NaN,D
236019,64,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Ward No. 23,Venkatagiri,Nellore,...,24-04-2017 20:50,2000,Modern Eye Hospital and Research Centre,C,Nellore,15-03-2017 00:00,15-03-2017 00:00,NO,NaN,D
253139,48,Male,OC,S15,POLY TRAUMA,S15.8.1,Surgical Management with Facial Bone Fractures...,Darsi,Darsi,Prakasam,...,15-05-2017 22:22,15300,Nalluri Nursing Home,C,Prakasam,01-04-2017 00:00,05-04-2017 00:00,NO,NaN,D
256228,43,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Kodurupadu,Bhimadole,West Godavari,...,10-05-2017 19:27,2040,Pushpagiri Eye Hospital,C,Hyderabad,01-04-2017 00:00,06-04-2017 00:00,NO,NaN,D
260371,43,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Kodurupadu,Bhimadole,West Godavari,...,10-05-2017 19:07,2040,Pushpagiri Eye Hospital,C,Hyderabad,06-04-2017 00:00,06-04-2017 00:00,NO,NaN,D
265591,43,Female,Minorities,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Ward 24,Rayachoti (M),YSR Kadapa,...,15-05-2017 20:39,2000,SURENDRA MULTISPECAILITY HOSPITALS,C,Chittoor,15-04-2017 00:00,16-04-2017 00:00,NO,NaN,D
281968,41,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.2.7,Amniotic Membrane Graft for Cornea/Sclera (12....,Galavilli,Balajipeta,Vizianagaram,...,30-05-2017 21:09,11000,Shankar Foundation And Eye Institute,C,Vishakhapatnam,22-04-2017 00:00,24-04-2017 00:00,NO,NaN,D
286382,48,Female,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,26th Ward,Rajahmundry(M),East Godavari,...,16-05-2017 20:09,2000,AKIRA EYE HOSPITAL,C,East Godavari,27-04-2017 00:00,27-04-2017 00:00,NO,NaN,D
288894,41,Male,OC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Nandamuru,Kovvuru,West Godavari,...,17-05-2017 20:11,2000,Goutami Eye Institute,C,East Godavari,29-04-2017 00:00,29-04-2017 00:00,NO,NaN,D
298564,42,Male,BC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,TATAIAH NAGAR,TIRUPATHI URBAN,Chittoor,...,29-05-2017 21:44,2000,SURENDRA MULTISPECAILITY HOSPITALS,C,Chittoor,11-05-2017 00:00,12-05-2017 00:00,NO,NaN,D
304855,54,Female,SC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,Purushothapatnam,Seethanagaram,East Godavari,...,06-06-2017 20:47,2000,AKIRA EYE HOSPITAL,C,East Godavari,11-05-2017 00:00,12-05-2017 00:00,NO,NaN,D
313895,55,Male,OC,S3,OPHTHALMOLOGY SURGERY,S3.3.5,Photocoagulation for Retinopathy,15th Ward,Rajahmundry(M),East Godavari,...,04-07-2017 21:18,2040,Pushpagiri Eye Hospital,C,Hyderabad,19-05-2017 00:00,20-05-2017 00:00,NO,NaN,D
314601,30,Female,BC,S15,POLY TRAUMA,S15.6.3,Surgical Management of wound In Compound Fract...,Thummalapenta,Kavali,Nellore,...,19-08-2017 20:07,15000,Kandukuri Hospital,C,Nellore,15-05-2017 00:00,22-05-2017 00:00,NO,NaN,D
314602,30,Female,BC,S15,POLY TRAUMA,S15.6.2,Surgical Management of Grade III Compound Frac...,Thummalapenta,Kavali,Nellore,...,19-08-2017 20:07,15000,Kandukuri Hospital,C,Nellore,15-05-2017 00:00,22-05-2017 00:00,NO,NaN,D
314603,30,Female,BC,S15,POLY TRAUMA,S15.7.2,Surgical management with K-Wiring for Small bo...,Thummalapenta,Kavali,Nellore,...,19-08-2017 20:07,15000,Kandukuri Hospital,C,Nellore,15-05-2017 00:00,22-05-2017 00:00,NO,NaN,D

In [ ]:
df.columns #['T/r', 'Kategoriya kodi', 'Operatsiya kodi', 'Tuman (yoki mahalla) nomi', 'Tuman nomi', 'Shifoxona joylashgan tuman']

Index(['yosh', 'jinsi', 'kasta_nomi', 'kategoriya_kodi', 'kategoriya_nomi',
       'operatsiya_kodi', 'operatsiya', 'qishloq', 'familiya', 'viloyat',
       'oldindan_tasdiqlash_sanasi', 'oldindan_tasdiqlash_summasi',
       'davo_sanasi', 'davo_summasi', 'shifoxona_nomi', 'shifoxona_turi',
       'shifoxona_joylashgan_viloyat', 'Operatsiya_sana',
       'uyga_chiqarilgan_sana', 'hayotmi', 'olim_sanasi',
       'royxatdan_otgan_manba'],
      dtype='object')

In [ ]:
df = df.reset_index()
df

,index,t_r,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
0,0,1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,1,2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,2,3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,3,4,45,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Telikipenta,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,4,5,54,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Thandemvalasa,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,335389,335390,65,Male,SC,S3,OPHTHALMOLOGY SURGERY,SU66,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,...,04-08-2017 21:23,23320,Sankar Eye Hospital,C,Guntur,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,335390,335391,54,Female,OC,S12,MEDICAL ONCOLOGY,S12.1.4,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,...,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,Hyderabad,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,335391,335392,19,Female,SC,S12,MEDICAL ONCOLOGY,S12.28.1,Palliative Chemotherapy for unlisted Regimen,Vinduru,...,04-10-2017 19:46,5000,M.N.J.Hospitals,G,Hyderabad,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,335392,335393,50,Male,BC,S9,GENITO URINARY SURGERIES,S9.3.4,ursl,Duppituru,...,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,Vishakhapatnam,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,335393,335394,46,Female,SC,S12,MEDICAL ONCOLOGY,S12.2.1,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,...,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,East Godavari,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

#### **2-mashq**. Datasetdagi quyidagi ustunlar o'chirib yuborilsin:<br>
*   Sno
*   CATEGORY_CODE
*   SURGERY_CODE
*   MANDAL_NAME
*   DISTRICT_NAME
*   HOSP_DISTRICT
<BR>

In [ ]:
# Javobni shuyerga yozing
df1 = df.drop(['t_r','kategoriya_kodi','operatsiya_kodi','qishloq','familiya','viloyat','shifoxona_joylashgan_viloyat'], axis=1)
df1

,index,yosh,jinsi,kasta_nomi,kategoriya_nomi,operatsiya,oldindan_tasdiqlash_sanasi,oldindan_tasdiqlash_summasi,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
0,0,56,Female,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,1,37,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,2,50,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,3,45,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,4,54,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,335389,65,Male,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,C,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,335390,54,Female,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,335391,19,Female,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,G,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,335392,50,Male,BC,GENITO URINARY SURGERIES,ursl,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,335393,46,Female,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

#### **3-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni unique funksiyasi orqali tekshiring.

In [ ]:
# Javobni shuyerga yozing
df['jinsi'].unique()

array([nan])

#### **4-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni **Erkak** va **Ayol** ga o'zgartiring:
O'zgartirish quyidagicha bo'lsin:


*   Male -> Erkak
*   Male(child) -> Erkak
*   Female - > Ayol
*   Female(child) - Ayol
*   MALE -> Erkak
*   FEMALE -> Ayol

In [ ]:
# Javobni shuyerga yozing
dict = {"Male":"erkak", "Male(child)":"erkak","Female":"ayol","Female(child)":"ayol","MALE":"erkak","FEMALE":"ayol"}
df['jinsi'] = df['jinsi'].map(dict).fillna(df['jinsi'])
df

<ipython-input-53-257065fefa95>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['jinsi'] = df['jinsi'].map(dict).fillna(df['jinsi'])

,index,t_r,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
0,0,1,56,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,1,2,37,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,2,3,50,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,3,4,45,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Telikipenta,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,4,5,54,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Thandemvalasa,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,335389,335390,65,NaN,SC,S3,OPHTHALMOLOGY SURGERY,SU66,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,...,04-08-2017 21:23,23320,Sankar Eye Hospital,C,Guntur,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,335390,335391,54,NaN,OC,S12,MEDICAL ONCOLOGY,S12.1.4,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,...,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,Hyderabad,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,335391,335392,19,NaN,SC,S12,MEDICAL ONCOLOGY,S12.28.1,Palliative Chemotherapy for unlisted Regimen,Vinduru,...,04-10-2017 19:46,5000,M.N.J.Hospitals,G,Hyderabad,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,335392,335393,50,NaN,BC,S9,GENITO URINARY SURGERIES,S9.3.4,ursl,Duppituru,...,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,Vishakhapatnam,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,335393,335394,46,NaN,SC,S12,MEDICAL ONCOLOGY,S12.2.1,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,...,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,East Godavari,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

#### **5-mashq**. Endi xuddi shu SEX columndagi ma'lumotlarni raqamlarga o'zgartiring: Erkaklarni 1 raqamiga, Ayollarni 0 raqamiga o'zgartiring.
*   Erkak -> 1
*   Ayol -> 0

In [ ]:
# Javobni shuyerga yozing

#### **6-mashq**. Shu jarayonni HOSP_TYPE ustuni uchun ham amalga oshiring.
*   G - General hospital (umumiy kasalxona) degani
*   C - Special hospital (maxsus kasalxona) degani
<br><b>O'zgarish quyidagicha bo'lsin:</b>
*   G -> Umumiy
*   C -> Maxsus

In [ ]:
# Javobni shuyerga yozing
df.columns
df[['shifoxona_turi']] # shifonalarni chiqarib oldik
df['shifoxona_turi'].unique()
dict = {"G":"umumiy","S":"maxsus"}
df['shifoxona_turi'].map(dict)

0         umumiy
1         umumiy
2         umumiy
3         umumiy
4         umumiy
           ...
335389       NaN
335390       NaN
335391    umumiy
335392       NaN
335393       NaN
Name: shifoxona_turi, Length: 335394, dtype: object

#### **7-mashq**. O'zgartirish amalga oshirilgach, HOSP_TYPE ustunida qancha Umumiy va qancha Maxsus kasalxonalar borligini ham aniqlang

In [ ]:
# Javobni shuyerga yozing
df['shifoxona_turi'].value_counts()

shifoxona_turi
C    241139
G     94255
Name: count, dtype: int64

#### **8-mashq**. Datasetda qancha takrorlangan qatorlar borligini aniqlang

In [ ]:
# Javobni shuyerga yozing
df.duplicated().value_counts()
#sum(df.duplicated())

False    335394
Name: count, dtype: int64

#### **9-mashq**. Datasetda barcha takrorlangan qatorlarni o'chirib yuboring

In [ ]:
# Javobni shuyerga yozing
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
335389    False
335390    False
335391    False
335392    False
335393    False
Length: 335394, dtype: bool

In [ ]:
df.columns

Index(['index', 't_r', 'yosh', 'jinsi', 'kasta_nomi', 'kategoriya_kodi',
       'kategoriya_nomi', 'operatsiya_kodi', 'operatsiya', 'qishloq',
       'familiya', 'viloyat', 'oldindan_tasdiqlash_sanasi',
       'oldindan_tasdiqlash_summasi', 'davo_sanasi', 'davo_summasi',
       'shifoxona_nomi', 'shifoxona_turi', 'shifoxona_joylashgan_viloyat',
       'Operatsiya_sana', 'uyga_chiqarilgan_sana', 'hayotmi', 'olim_sanasi',
       'royxatdan_otgan_manba'],
      dtype='object')

#### **10-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning o'rtacha qiymatlarini toping.

In [ ]:
# Javobni shuyerga yozing
df.groupby("shifoxona_turi")["davo_summasi"].mean()

shifoxona_turi
C    30272.214457
G    22683.900769
Name: davo_summasi, dtype: float64

#### **11-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning minimum qiymatlarini toping.

In [ ]:
# Javobni shuyerga yozing
df.groupby("shifoxona_turi")["davo_summasi"].min()

shifoxona_turi
C    2
G    2
Name: davo_summasi, dtype: int64

#### **12-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), CLAIM_AMOUNTning maksimum qiymatlarini toping.

In [ ]:
# Javobni shuyerga yozing
df.groupby("shifoxona_turi")["davo_summasi"].max()

shifoxona_turi
C    520000
G    520000
Name: davo_summasi, dtype: int64

.agg() yordamida istalgan funksiyalarni chaqirishimiz mumkin, misol uchun numpy dagi mean (o'rta qiymat) funiksiyasini ham qo'shamiz. Natijalarni faqat price ustuni uchun chiqaramiz:

In [ ]:
df.head()

,index,t_r,yosh,jinsi,kasta_nomi,kategoriya_kodi,kategoriya_nomi,operatsiya_kodi,operatsiya,qishloq,...,davo_sanasi,davo_summasi,shifoxona_nomi,shifoxona_turi,shifoxona_joylashgan_viloyat,Operatsiya_sana,uyga_chiqarilgan_sana,hayotmi,olim_sanasi,royxatdan_otgan_manba
0,0,1,56,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,1,2,37,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,2,3,50,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,3,4,45,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Telikipenta,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,4,5,54,NaN,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Thandemvalasa,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D

#### **13-mashq**. Datasetdan jinsiga ko'ra CLAIM_AMOUNTning min, max va o'rta qiymatlarni agg() usuli yordamida toping.

In [ ]:
# Javobni shuyerga yozing
df.groupby("yosh")["davo_summasi"].agg(["min", "max", "mean"])

        min     max          mean
yosh
0      1000  520000  31658.075340
1      1000  520000  38424.015045
2      2000  520000  28130.172721
3         2  520000  28073.329173
4         2  520000  28222.820637
...     ...     ...           ...
95    10000   30000  24775.000000
96    12500   30000  19971.428571
100   30000   30000  30000.000000
101   30000   30000  30000.000000
107   10000   30000  20000.000000

[100 rows x 3 columns]

In [ ]:
df.index

RangeIndex(start=0, stop=335394, step=1)